// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bwcSSYqcBXtyPeXvFEu2Rh
// Component: weOmw-gDEiORk0
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection2 from "../../HeroSection2"; // plasmic-import: v1jhYcAfG7LOtI/component
import Button from "../../Button"; // plasmic-import: j1CvLaKdoY_PwW/component
import Divider from "../../Divider"; // plasmic-import: 5L5Evdtd83p343/component
import Textinput from "../../Textinput"; // plasmic-import: Es-_roA0MbFZVS/component
import Navigation from "../../Navigation"; // plasmic-import: Cy8JPfTpOlvQpI/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: EQ4lRdVwh5ykuJ/component
import Valueprop from "../../Valueprop"; // plasmic-import: E6wHDTjYujWRMk/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: jZbOS1USrsTwhp/component
import ListItem from "../../ListItem"; // plasmic-import: fTjvXvQskmdeA4/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: 0ACWzV1zIg8ldV/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: Byj8_PspKHSRUe/component
import Banner from "../../Banner"; // plasmic-import: XFCbHd8oXlj2iE/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: 3X4t1REQFADgrH/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: qN9seyViMez1wk/component
import Testimonial from "../../Testimonial"; // plasmic-import: VOSEbsRev_xNj-/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: NGOcbeGFRSOOTy/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nGxlWJ9rXiT6sF/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: bwcSSYqcBXtyPeXvFEu2Rh/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: weOmw-gDEiORk0/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 3bOHmE97YcNirE/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: uV22ZdjZ_81n5B/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: 0NRc8qbLXIdbue/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: RZTYhUuxj-fPZb/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: NQC9CEyZtelPIk/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: B7TCtFLMb1MeCQ/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: VP2k7m_LNMWi0i/icon
import image131Tr6Yur8066MUm from "./images/image13.svg"; // plasmic-import: 1tr6YUR8066MUm/picture
import loomsvg2Rm9R6KaEssgkE6 from "./images/loomsvg2.svg"; // plasmic-import: rm9r6KAEssgkE6/picture
import strapisvg2Tn9C8TR7MvmLcg from "./images/strapisvg2.svg"; // plasmic-import: Tn9C8tR7mvmLcg/picture
import segmentsvg2Ux7BhTcHEc96 from "./images/segmentsvg2.svg"; // plasmic-import: UX7-BHTcH-Ec96/picture
import xstate1SvgO2QJjJjoGl4Uyp from "./images/xstate1Svg.svg"; // plasmic-import: O2qJJJjoGl4Uyp/picture
import mapboxsvg2C7BUiTbWta9Tuc from "./images/mapboxsvg2.svg"; // plasmic-import: C7bUITbWTA9Tuc/picture

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  heroSection2?: p.Flex<typeof HeroSection2>;
  navigation?: p.Flex<typeof Navigation>;
  valuesSection3?: p.Flex<typeof ValuesSection3>;
  h2?: p.Flex<"h2">;
  valuesSection2Dark?: p.Flex<typeof ValuesSection2Dark>;
  pricingSection3?: p.Flex<typeof PricingSection3>;
  shopBanners?: p.Flex<typeof ShopBanners>;
  logoCloudSection2?: p.Flex<typeof LogoCloudSection2>;
  testimonialsSection1?: p.Flex<typeof TestimonialsSection1>;
  callToActionSection1?: p.Flex<typeof CallToActionSection1>;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__n9FmJ)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__d5EN6)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__yJnzK)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__udjun
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__pWmy5
                      )}
                    >
                      <span>
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span style={{ textDecoration: "underline" }}>
                          {"adapt"}
                        </span>
                      </span>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gy9U
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__zSbHn)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__eyNim
                      )}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__bCrVt
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      }
                    />

                    <Button
                      bgDifference={"bgDifference" as const}
                      className={classNames("__wab_instance", sty.button__oLnx)}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__e2Tjv
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__mLfW8)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__rwZQt)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__j4YqK)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__tnv27
                        )}
                      >
                        {"Sign up with"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___9ArGl
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__b9HjS
                          )}
                          ouline={"ouline" as const}
                          slot={"Apple"}
                          startIcon={"startIcon" as const}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__pPKey
                          )}
                          ouline={"ouline" as const}
                          slot={"Google"}
                          startIcon={"startIcon" as const}
                        >
                          <Icon6Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__kJ17
                            )}
                            role={"img"}
                          />
                        </Button>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.freeBox__jvS)}
                      >
                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__c2WO
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__kUnq
                          )}
                        >
                          {"Or"}
                        </div>

                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__hxklI
                          )}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__nWitT
                        )}
                      >
                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__wk0QR
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput___7DEnu
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__j5TvQ
                          )}
                        />
                      </p.Stack>

                      <Button
                        children2={
                          <Icon5Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___5MShd
                            )}
                            role={"img"}
                          />
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button__aaI0L
                        )}
                        colors={"indigo" as const}
                        slot={"Start your account"}
                      />
                    </p.Stack>

                    <Divider
                      className={classNames(
                        "__wab_instance",
                        sty.divider__ibQp
                      )}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__lEtBd)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__qxNYt
                        )}
                      >
                        {
                          "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
                        }
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          >
            <Navigation
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames("__wab_instance", sty.navigation)}
              hideCta={"hideCta" as const}
              slot={
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button__gBgb)}
                    link={"#services" as const}
                    navLink={"navLink" as const}
                    slot={"Services"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__o7ViK)}
                    link={"#features" as const}
                    navLink={"navLink" as const}
                    slot={"Features"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__eosgh)}
                    link={"#pricing" as const}
                    navLink={"navLink" as const}
                    slot={"Pricing"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__pswKa)}
                    link={"#testimonials" as const}
                    navLink={"navLink" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__hXm4
                        )}
                      >
                        {"Testimonials"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___5AigF)}
                    navLink={"navLink" as const}
                    slot={"Log in"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___56P3E)}
                    darkGray={"darkGray" as const}
                    slot={"Sign up"}
                  />
                </React.Fragment>
              }
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__hPq84)}
                role={"img"}
                src={image131Tr6Yur8066MUm}
              />
            </Navigation>
          </HeroSection2>

          <div
            className={classNames(defaultcss.all, sty.freeBox__pbLmt)}
            id={"services" as const}
          >
            <ValuesSection3
              data-plasmic-name={"valuesSection3"}
              data-plasmic-override={overrides.valuesSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___7Hl1R)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___8Xcri
                      )}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          defaultcss.h2,
                          defaultcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Proposing values"}
                      </h2>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__dtRbg
                      )}
                    >
                      {
                        "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__aly2)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__iw3CP)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__vBQcw
                        )}
                        flat={"flat" as const}
                        slot={
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__oOx5G
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Powerful"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__qkNfK
                        )}
                        flat={"flat" as const}
                        slot={
                          "Consequat scelerisque a eros taciti nisl a sodales."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__xjRkN
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Faster"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__aIeE7
                        )}
                        flat={"flat" as const}
                        slot={"At ut condimentum amet adipiscing ac diam a."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__wXrYe
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Best and brightest"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__baDa1
                        )}
                        flat={"flat" as const}
                        slot={
                          "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__bdGpw
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__mSkMf
                          )}
                        >
                          {"Dynamic range"}
                        </div>
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__xsuTn)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__twrWj)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__yYqIa
                        )}
                        flat={"flat" as const}
                        slot={
                          "Commodo pretium himenaeos nisi potenti ad in ante."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___8SBam
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__jru1F
                          )}
                        >
                          {"Portable"}
                        </div>
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___0BsP1
                        )}
                        flat={"flat" as const}
                        slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__sshDn
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Production-ready"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__o4Riw
                        )}
                        flat={"flat" as const}
                        slot={
                          "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pciSi
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Magical"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__w50Je
                        )}
                        flat={"flat" as const}
                        slot={
                          "A parturient mi suspendisse nisl inceptos nullam a."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___1LxT8
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Accessible"}
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox__xIwX0)}
            id={"features" as const}
          >
            <ValuesSection2Dark
              data-plasmic-name={"valuesSection2Dark"}
              data-plasmic-override={overrides.valuesSection2Dark}
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox__raW1M)}
            id={"pricing" as const}
          >
            <PricingSection3
              data-plasmic-name={"pricingSection3"}
              data-plasmic-override={overrides.pricingSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__xiBsV)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___0ArxV
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__q6Kfu
                        )}
                      >
                        {"Pricing plans"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__uSq5U
                      )}
                    >
                      {
                        "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___3Guwc)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__hG5Mb)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__a6NHc
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___9Ipsc
                          )}
                        >
                          {"Starter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__cEWkZ
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__hj2UA
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__o0Qz3
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__kbrjW
                              )}
                            >
                              {"8"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__gfMua
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__kD3R
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__vomDr
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__wmRqz
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__l7Sfs
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__nscc8
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__jpeXr
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__js0Gc
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Mus consequat a justo"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__pZwhk
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__z03Xy
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__cCOyL
                              )}
                            >
                              {"Buy starter"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__mbZqc)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__dfk6K
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__rGreq
                          )}
                        >
                          {"Pro"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__jpe7T
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__rmb16
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox___7CAa
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox___96Az
                              )}
                            >
                              {"16"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__rmSab
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__iYuG9
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__p1Yyl
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__lU3Vs
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__i3NyT
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Ligula primis mollis sem dignissim semper lectus parturient"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__yvVr
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__iaEqi
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___0L6C4
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__oqVGr
                                )}
                              >
                                {
                                  "A curabitur dignissim pharetra porta suscipit"
                                }
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__v7Ii0
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___8WDFx
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__t9R
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Condimentum diam a et sapien praesent potenti torquent a eros"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__kkp6R
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__wUkaV
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__spUgk
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__nPoh
                                )}
                              >
                                {"Conubia in hac eu elementum sodales"}
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__xG2D
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__pW7Wo
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"green" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__o6Muw
                              )}
                            >
                              {"Buy pro"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___96QcV
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__x9Fp4
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__wZz7N
                          )}
                        >
                          {"Team"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__f9Qy
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__mIx2G
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__cfnxC
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__utsBp
                              )}
                            >
                              {"10"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox___5Toe7
                            )}
                          >
                            {"/member"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider___36AcD
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__ipVja
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__xWgCp
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__mJkvR
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Ad nam curae a potenti platea"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__qNFsn
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___74DGq
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__wueC
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "A adipiscing scelerisque pretium consectetur sem"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__oLqGf
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__rHzA
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__sx5R8
                              )}
                            >
                              {"Buy team"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          >
            <Banner
              className={classNames("__wab_instance", sty.banner__rIJg)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__e9S9U
                    )}
                  >
                    {"Sunglasses Collection"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__urEqj
                    )}
                  >
                    {"Get 25% off on selected items"}
                  </div>

                  <Button
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__dqN2B
                        )}
                      >
                        {"Go to collection ->"}
                      </div>
                    }
                  />
                </React.Fragment>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__ibevn)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__fvjrg)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__lLmx
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__tLenx
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__wJher
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__qzrfC)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80" as const
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner__l2TvK)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__suiem
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gt0JP
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___6JteN
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__yA4Rp)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80" as const
                  }
                />
              </Banner>
            </p.Stack>
          </ShopBanners>

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <div
            className={classNames(defaultcss.all, sty.freeBox___7QLms)}
            id={"testimonials" as const}
          >
            <TestimonialsSection1
              data-plasmic-name={"testimonialsSection1"}
              data-plasmic-override={overrides.testimonialsSection1}
            >
              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___2LYsX
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__smfuU)}
                    role={"img"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj" as const
                    }
                  />
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__iSrbf)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__hVbaV)}
                    role={"img"}
                    src={
                      "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png" as const
                    }
                  />
                }
                slot2={"Elaine Benes"}
                slot3={"Editor, Pendant Publishing"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__qanku
                  )}
                >
                  {'"Vestibulum lacinia varius habitant dis aenean.'}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__gjrPk
                  )}
                >
                  {
                    'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___66EgB
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__zbB5A)}
                    role={"img"}
                    src={
                      "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg" as const
                    }
                  />
                }
                slot2={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__lYSgV
                    )}
                  >
                    {"Woody Boyd"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__oxhfl
                    )}
                  >
                    {"Assistant Bartender, Cheers"}
                  </div>
                }
              >
                {
                  '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
                }
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__y7G0C)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3PGzz)}
                    role={"img"}
                    src={
                      "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg" as const
                    }
                  />
                }
                slot2={"Louis Huang"}
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__ntZsR
                    )}
                  >
                    {"Restaurant Owner, Cattleman's Ranch"}
                  </div>
                }
              >
                {
                  '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                }
              </Testimonial>
            </TestimonialsSection1>
          </div>

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection2",
    "navigation",
    "valuesSection3",
    "h2",
    "valuesSection2Dark",
    "pricingSection3",
    "shopBanners",
    "logoCloudSection2",
    "testimonialsSection1",
    "callToActionSection1"
  ],
  heroSection2: ["heroSection2", "navigation"],
  navigation: ["navigation"],
  valuesSection3: ["valuesSection3", "h2"],
  h2: ["h2"],
  valuesSection2Dark: ["valuesSection2Dark"],
  pricingSection3: ["pricingSection3"],
  shopBanners: ["shopBanners"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  callToActionSection1: ["callToActionSection1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection2: typeof HeroSection2;
  navigation: typeof Navigation;
  valuesSection3: typeof ValuesSection3;
  h2: "h2";
  valuesSection2Dark: typeof ValuesSection2Dark;
  pricingSection3: typeof PricingSection3;
  shopBanners: typeof ShopBanners;
  logoCloudSection2: typeof LogoCloudSection2;
  testimonialsSection1: typeof TestimonialsSection1;
  callToActionSection1: typeof CallToActionSection1;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection2: makeNodeComponent("heroSection2"),
    navigation: makeNodeComponent("navigation"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    h2: makeNodeComponent("h2"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    shopBanners: makeNodeComponent("shopBanners"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
