// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bwcSSYqcBXtyPeXvFEu2Rh
// Component: Es-_roA0MbFZVS
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: bwcSSYqcBXtyPeXvFEu2Rh/projectcss
import * as sty from "./PlasmicTextinput.module.css"; // plasmic-import: Es-_roA0MbFZVS/css

export type PlasmicTextinput__VariantMembers = {};

export type PlasmicTextinput__VariantsArgs = {};
type VariantPropType = keyof PlasmicTextinput__VariantsArgs;
export const PlasmicTextinput__VariantProps = new Array<VariantPropType>();

export type PlasmicTextinput__ArgsType = {};
type ArgPropType = keyof PlasmicTextinput__ArgsType;
export const PlasmicTextinput__ArgProps = new Array<ArgPropType>();

export type PlasmicTextinput__OverridesType = {
  root?: p.Flex<"input">;
};

export interface DefaultTextinputProps {
  className?: string;
}

function PlasmicTextinput__RenderFunc(props: {
  variants: PlasmicTextinput__VariantsArgs;
  args: PlasmicTextinput__ArgsType;
  overrides: PlasmicTextinput__OverridesType;
  dataFetches?: PlasmicTextinput__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <input
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.input, projectcss.root_reset, sty.root)}
      placeholder={"Some placeholder" as const}
      size={1 as const}
      type={"text" as const}
      value={"Some value" as const}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTextinput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTextinput__VariantsArgs;
    args?: PlasmicTextinput__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTextinput__Fetches;
  } & Omit<PlasmicTextinput__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTextinput__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTextinput__ArgProps,
      internalVariantPropNames: PlasmicTextinput__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTextinput__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTextinput";
  } else {
    func.displayName = `PlasmicTextinput.${nodeName}`;
  }
  return func;
}

export const PlasmicTextinput = Object.assign(
  // Top-level PlasmicTextinput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTextinput
    internalVariantProps: PlasmicTextinput__VariantProps,
    internalArgProps: PlasmicTextinput__ArgProps
  }
);

export default PlasmicTextinput;
/* prettier-ignore-end */
